### ISSUE TITLE
Save hukamnama everyday and provide ability to open hukam from a certain date

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/banidb-api#5]
From @prebhdevsingh:

We should save the shabad ID of the hukamnama in a table and provide ability to look up a hukamnama by entering a date.

**Comment by davchana** [comment]
Yes, & please add info too to that table->date

````
hukaminfo:
     status:(success) //if fetched correctly
     source: (Gurudwara|Harmandir Sahib)
     bani: (SGGS|?)
     time: (am|pm)
````
